# Generated by Django 5.1 on 2024-08-30 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('param_type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('range', 'Range')], max_length=10)),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('article_number', models.PositiveIntegerField(verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Косметику',
                'verbose_name_plural': 'Косметика',
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_min', models.IntegerField(blank=True, null=True)),
                ('value_max', models.IntegerField(blank=True, null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parameter')),
                ('products', models.ManyToManyField(related_name='parameter_values', to='core.product')),
            ],
        ),
    ]
