# Generated by Django 5.1 on 2024-08-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'verbose_name': 'Значение', 'verbose_name_plural': 'Значения параметров'},
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='param_type',
            field=models.CharField(choices=[('str', 'Строка'), ('int', 'Число'), ('range', 'Диапазон')], max_length=10, verbose_name='Тип параметра'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='value_int',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='value_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение до'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='value_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значения от'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='value_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение'),
        ),
    ]
