# Generated by Django 5.1 on 2024-09-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_parametervalue_options_alter_parameter_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Параметры', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'ordering': ['value_str', 'value_int', 'value_min'], 'verbose_name': 'Значение', 'verbose_name_plural': 'Значения параметров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Косметика', 'verbose_name_plural': 'Косметика'},
        ),
        migrations.AddField(
            model_name='product',
            name='clear',
            field=models.BooleanField(default=False, verbose_name='Очищение'),
        ),
        migrations.AddField(
            model_name='product',
            name='evening_program',
            field=models.BooleanField(default=False, verbose_name='Вечерняя программа'),
        ),
        migrations.AddField(
            model_name='product',
            name='frequency_of_use',
            field=models.IntegerField(default=1, verbose_name='Частота использования'),
        ),
        migrations.AddField(
            model_name='product',
            name='humidification',
            field=models.BooleanField(default=False, verbose_name='Увлажнение'),
        ),
        migrations.AddField(
            model_name='product',
            name='morning_program',
            field=models.BooleanField(default=False, verbose_name='Утренняя программа'),
        ),
        migrations.AddField(
            model_name='product',
            name='night_cream',
            field=models.BooleanField(default=False, verbose_name='Ночной крем/маска'),
        ),
        migrations.AddField(
            model_name='product',
            name='peeling',
            field=models.BooleanField(default=False, verbose_name='Пилинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='protection',
            field=models.BooleanField(default=False, verbose_name='Защита'),
        ),
        migrations.AddField(
            model_name='product',
            name='serum',
            field=models.BooleanField(default=False, verbose_name='Сыворотка'),
        ),
        migrations.AddField(
            model_name='product',
            name='toning',
            field=models.BooleanField(default=False, verbose_name='Тонизирование'),
        ),
    ]
