# Generated by Django 5.1 on 2024-09-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_parameter_options_alter_parametervalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название программы')),
                ('order', models.PositiveIntegerField(help_text='Порядок применения продуктов в программе', verbose_name='Порядок')),
                ('time_to_send', models.TimeField(verbose_name='Время отправки программы')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название свойства')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок использования')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='clear',
        ),
        migrations.RemoveField(
            model_name='product',
            name='evening_program',
        ),
        migrations.RemoveField(
            model_name='product',
            name='humidification',
        ),
        migrations.RemoveField(
            model_name='product',
            name='morning_program',
        ),
        migrations.RemoveField(
            model_name='product',
            name='night_cream',
        ),
        migrations.RemoveField(
            model_name='product',
            name='peeling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serum',
        ),
        migrations.RemoveField(
            model_name='product',
            name='toning',
        ),
        migrations.AlterField(
            model_name='product',
            name='frequency_of_use',
            field=models.PositiveIntegerField(default=1, verbose_name='Частота использования (в днях)'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя из чата')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата старта программы')),
                ('duration', models.PositiveIntegerField(default=100, verbose_name='Длительность программы в днях')),
                ('products', models.ManyToManyField(to='core.product', verbose_name='Продукты программы')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programtype', verbose_name='Тип программы')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(to='core.property', verbose_name='Свойства'),
        ),
        migrations.CreateModel(
            name='SkincareProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID пользователя в боте')),
                ('last_sent', models.DateField(blank=True, null=True, verbose_name='Последняя отправка')),
                ('program_type', models.CharField(choices=[('morning', 'Утро'), ('evening', 'Вечер')], max_length=10, verbose_name='Тип программы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
            ],
        ),
    ]
