# Generated by Django 5.1 on 2024-09-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_programtype_property_remove_product_clear_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программы', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Свойства', 'verbose_name_plural': 'Свойства'},
        ),
        migrations.RemoveField(
            model_name='programtype',
            name='order',
        ),
    ]
