# Generated by Django 5.1 on 2024-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_program_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtype',
            options={'verbose_name': 'Тип программы', 'verbose_name_plural': 'Тип программы'},
        ),
        migrations.AddField(
            model_name='property',
            name='program_types',
            field=models.ManyToManyField(related_name='properties', to='core.programtype', verbose_name='Типы программы'),
        ),
    ]
